### ISSUE TITLE
{connection_id}/profile does not allow multiple simultaneously active profiles

### ISSUE THREAD

**Issue by Stroomversnelling** [Stroomversnelling/monitoring_api#11]
**Describe the bug**
Wanneer je meerdere profielen ondersteunt, hoe geef je dit weer in de {connection_id}/profile call en hoe kan je zeggen welke objecten dan bij welk profiel horen?
> Ai, dit is een oversight van onze kant! Daar hebben we het wel over gehad, maar dat is niet tot uitdrukking gekomen in hoe de /profile call nu in elkaar steekt. Het zal moeten zitten in het toevoegen van een niveau, zodat je een array krijgt van profiles. Dat voeg ik toe als urgent issue.

**Comment by nickdickinson** [comment]
At the moment, we are considering changing the way that one queries data_objects under a profile. For example, if we precisely define profile names to refer to specific norms/standards, then we can use the following example to get all objects following profile's definition:
/{connection_id}/profile/{profile_name}/

Alternatively, we could specify the high level variable under that profile to get a time series, such as:
/{connection_id}/profile/monitoring_norm_1_0/E_gen

This would then return unambiguously the connection's data_object for E_gen and related time series respecting the profile for the monitoring norm 1.0.

**Comment by Stroomversnelling** [comment]
Fixed.
