### ISSUE TITLE
IS8601 or RFC3339?

### ISSUE THREAD

**Issue by FilipAben** [Stroomversnelling/monitoring_api#14]
**Describe the bug**
The wiki explicitly says "Date and time formats are defined by ISO8601"
Some API definitions, such as 'start_time' in data_objects/{connection_id} state 
"Starting time of requested measurements in seconds (yyyy-mm-dd hh:im:ss , inclusive)". This most likely refers to RFC3339 where it is allowed to use a space instead of 'T' for separating date & time.
But this seems not be allowed in ISO8601 (only omission if no confusion)

**Expected behavior**
A single consistent, machine-readable way of representing date & time values. I would prefer ISO8601 as "yyyy-mm-ddThh:mm:ss" as this enjoys a wider support.

**Additional context**
References:
https://stackoverflow.com/questions/9531524/in-an-iso-8601-date-is-the-t-character-mandatory
http://dotat.at/tmp/ISO_8601-2004_E.pdf
https://www.rfc-editor.org/rfc/rfc3339.txt

**Comment by nickdickinson** [comment]
I'm happy with implementing it with the T as defined in ISO8601. This is also the format assumed with "date-time" in Swagger/OpenApi3 so it could also help in simplifying the implementation of both the UDB and PDB APIs. I suggest we make this change and will take it up.

**Comment by rsa2010** [comment]
Unix Epoch was decided as input for time objects, ISO8601 should be dropped

**Comment by Stroomversnelling** [comment]
Unix Epoch (POSIX) has been chosen, together with timezone (tzid) designation.
