### ISSUE TITLE
resolution vs option

### ISSUE THREAD

**Issue by FilipAben** [Stroomversnelling/monitoring_api#15]
**Describe the bug**
in data_objects/{connection_id}, it is unclear what the relation is between the 'resolution' query parameter and the 'option' parameter'.  Which aggregations would you be able to request with the 'option' parameters that you cannot request with start_time + end_time + resolution?

**Comment by FilipAben** [comment]
A possible explanation would be that with a 'resolution' in seconds you cannot accurately express a day/week/month/year interval.
But then my question is which one of these parameters would take precedence when requesting data?

My suggestion would be limit the resolution set to a fixed number of values such as
'1h', '24h', '1w', '1M', '1Y',...

Requesting random resolutions is out of the question for us anyway. We pre-calculate a number of resolutions and that's it. Calculating random resolutions on the fly on raw data puts a significant strain on the databases, increases latency & is not scalable.

**Comment by nickdickinson** [comment]
Agreed. Please also see #12 

We suggested a minutes value in integer for anything under 1h. It is possible that some metered data would be requested for example on a 10 or 15 minute basis. Should we provide a fixed time period of 15 minutes?

**Comment by rsa2010** [comment]
The configuration shows the minimal resolution of the database (in seconds).
Any other resolution would resolve to a best fit.
For instance if you have hour data in the database and would request a 6 hour resolution (without aggregation) you should give back the closest fit (1 hour resolution is the best fit in this case).
With aggregation it is clear that certain operations have been performed on the database and you are not expecting raw values.

**Comment by FilipAben** [comment]
It is, but it would make the returned data less usable to PDB users since it is unclear in what resolution the returned data would be.

EDIT: I see it's the same discussion as in #12

**Comment by Stroomversnelling** [comment]
Fixed.
