### ISSUE TITLE
Purpose of object_id parameter in data_objects/{connection_id}

### ISSUE THREAD

**Issue by FilipAben** [Stroomversnelling/monitoring_api#17]
**Describe the bug**
What is the purpose of the object_id query parameter in data_objects/{connection_id} ? There is also a data_objects parameters which is an array of data_object's. Wouldn't just specifying a single element in data_objects be equivalent to setting the object_id?

**Comment by nickdickinson** [comment]
I am not sure it is correctly specified altogether. Let's do this, which is more REST like:
{connection_id}/data_object/ --> array of data_objects
{connection_id}/data_object/{object_id} --> specific data_object

**Comment by Stroomversnelling** [comment]
Fixed.
