### ISSUE TITLE
Enhancement: data_objects/{connection_id}

### ISSUE THREAD

**Issue by FilipAben** [Stroomversnelling/monitoring_api#18]
The other 2 calls have the format {connection_id}/xxxxxx but the data_objects call is
data_objects/{connection_id}. Is there a reason for this?
Would be more consistent to use {connection_id}/data_objects

**Comment by nickdickinson** [comment]
See #17 

Agree that this is not consistent and should be changed.

**Comment by Stroomversnelling** [comment]
Fixed.
