### ISSUE TITLE
Add endpoint to query log

### ISSUE THREAD

**Issue by Stroomversnelling** [Stroomversnelling/monitoring_api#4]
**Is your feature request related to a problem? Please describe.**
There has to be a log book to document changes to the data. E.g. when a sensor is broken and a device has to be replaced.  

**Describe the solution you'd like**
A separate endpoint that queries the log book.

**Describe alternatives you've considered**
N/A

**Additional context**  
The query should consist of
* timestamp  
* waar slaat de verandering op (object_id)  
* eindpunt (property)  
* oude waarde  
* nieuwe waarde  
* toelichting (optioneel)

**Comment by wouterjsmit** [comment]
There should be a log entry for:
- System changes. (device changed)
- Data errors (exact shape and severity of error is undefined)

**Comment by Stroomversnelling** [comment]
Fixed.
