### ISSUE TITLE
extend the config endpoint to request all variables related to a specific norm

### ISSUE THREAD

**Issue by Stroomversnelling** [Stroomversnelling/monitoring_api#8]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to request all variables related to a specific norm in one call (e.g. EPV)

**Describe the solution you'd like**
{connection_id}/config/nomkeur1.0

**Describe alternatives you've considered**
Checking the variables per norm, then asking for every variable in turn.

**Additional context**
Someone has to document which variables are part of which norm. Perhaps the Stroomversnelling?

**Comment by FilipAben** [comment]
Shouldn't this be part of the {connection_id}/profile call then? My current understanding is that all objects related to specific norm need to be specified there. See also #5

**Comment by Stroomversnelling** [comment]
That's a good point, and perhaps indeed the best solution. We'll have a look at that again before updating the API.

**Comment by nickdickinson** [comment]
Can we combine config and profile? Is there a need to have separate endpoints / objects for these?

**Comment by nickdickinson** [comment]
# #
Duplicate of #11

**Comment by Stroomversnelling** [comment]
Fixed.
